### ISSUE TITLE
Question about dynamically setting length

### ISSUE THREAD

**Issue by btray77** [marcusstenbeck/remotion-template-audiogram#4]
It would be nice to be able to make this the length of the audio, not just hard coded 30 seconds.  What's the best way to do this?

**Comment by marcusstenbeck** [comment]
I haven't done this before, but I'd try [`getAudioDurationInSeconds()`](https://www.remotion.dev/docs/get-audio-duration-in-seconds) together with the approach here: [*Change metadata based on asynchronous information*](https://www.remotion.dev/docs/dynamic-metadata#change-metadata-based-on-asynchronous-information).

The duration is specified in this file https://github.com/marcusstenbeck/remotion-template-audiogram/blob/main/src/Video.tsx so try putting the code there.

**Comment by JonnyBurger** [comment]
^ This is the Remotion recommended way!
