### ISSUE TITLE
Eliminate or shorten the "audioOffsetInFrames=2000" delay.

### ISSUE THREAD

**Issue by SAYUK09** [marcusstenbeck/remotion-template-audiogram#7]
The 'audioOffsetInFrame' is set by default to '2000', which results in a 1-minute delay.
If the **audio clip** is less than a minute, then it would throw irrelevant error that might be misleading and trick to debug.

Following suggestions could help:
- Add a Comment as follows:
```jsx 
<Composition
id="Audiogram"
component={AudiogramComposition}
durationInFrames={durationInFrames}
fps={fps}
width={1080}
height={1080}
defaultProps={{
audioOffsetInFrames: 2000,  // This will result in 1min delay. Reduce according to the length of your clip.
source: staticFile('subtitles.srt'),
 }}
/>
```

- Set the `audioOffsetInFrames` to `0` by default

**Comment by Just-Moh-it** [comment]
Fixed by @JonnyBurger... Could close it 🙃

**Comment by JonnyBurger** [comment]
Yes! Thanks for the issue nonetheless 🙌
